// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3e3YRjHhoq6zaaFBUSjs78y_F1tFdJEA',
    appId: '1:823512435444:web:b9d34b241ef47817752ca1',
    messagingSenderId: '823512435444',
    projectId: 'zottz-4f12c',
    authDomain: 'zottz-4f12c.firebaseapp.com',
    storageBucket: 'zottz-4f12c.firebasestorage.app',
    measurementId: 'G-R92J1BEEQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlZLZtzwxes9QhDLh-88vQlv-VeWqpoyM',
    appId: '1:823512435444:android:a31d2545fe55668f752ca1',
    messagingSenderId: '823512435444',
    projectId: 'zottz-4f12c',
    storageBucket: 'zottz-4f12c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1K0HUMkdZv7g9IF_TuZBVD7w8Tu6AYV0',
    appId: '1:823512435444:ios:6becff472be69d05752ca1',
    messagingSenderId: '823512435444',
    projectId: 'zottz-4f12c',
    storageBucket: 'zottz-4f12c.firebasestorage.app',
    iosBundleId: 'com.example.zottzOt',
  );
}
